version: '3'
services:
  frontend: 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"

  nginx:
    image: nginx:alpine
    depends_on:
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  
      - ./src/main/resources/static:/usr/share/nginx/html

